"""Provider configuration management for Derek Agent Runner."""

import logging
import os
import re
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# Default Minimax Anthropic-compatible endpoint
MINIMAX_DEFAULT_BASE_URL = "https://api.minimax.io/anthropic"

# Project-level config dir (dev), falls back to home dir (installed)
_PROJECT_ROOT = Path(__file__).parent.parent.parent


def get_providers_file() -> Path:
    """Resolve providers.yaml path.

    Priority: {project_root}/.derek-agent/ > ~/.derek-agent/
    """
    project_path = _PROJECT_ROOT / ".derek-agent" / "providers.yaml"
    if project_path.exists():
        return project_path
    home_path = Path.home() / ".derek-agent" / "providers.yaml"
    if home_path.exists():
        return home_path
    # Default to project-level for dev
    return project_path


def get_providers_dir() -> Path:
    """Resolve .derek-agent directory for writing."""
    return _PROJECT_ROOT / ".derek-agent"


# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class ModelInfo(BaseModel):
    """Info about a specific model variant."""

    id: str
    name: str
    context_window: int = 131072
    reasoning: bool = False


class ProviderConfig(BaseModel):
    """Configuration for a single provider."""

    api_key: str = ""
    base_url: str = ""
    api_protocol: str = "anthropic"
    models: list[ModelInfo] = Field(default_factory=list)


class DefaultsConfig(BaseModel):
    """Global defaults."""

    provider: str = ""
    model: str = ""


class ProvidersConfig(BaseModel):
    """Root structure for providers.yaml."""

    providers: dict[str, ProviderConfig] = Field(default_factory=dict)
    defaults: DefaultsConfig = Field(default_factory=DefaultsConfig)


# ---------------------------------------------------------------------------
# File I/O
# ---------------------------------------------------------------------------

_ENV_VAR_RE = re.compile(r"^\$\{([A-Z_][A-Z0-9_]*)\}$")


def _resolve_value(raw: str) -> str:
    """Expand ${ENV_VAR} references; return raw string otherwise."""
    m = _ENV_VAR_RE.match(raw)
    if m:
        return os.environ.get(m.group(1), "")
    return raw


def load_providers() -> ProvidersConfig:
    """Load providers.yaml, returning empty config if missing."""
    path = get_providers_file()
    if not path.exists():
        return ProvidersConfig()
    with path.open(encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return ProvidersConfig.model_validate(data)


def save_providers(config: ProvidersConfig, path: Path | None = None) -> None:
    """Write providers.yaml with a readable header comment."""
    if path is None:
        path = get_providers_file()
    path.parent.mkdir(parents=True, exist_ok=True)

    raw = config.model_dump(exclude_none=True)

    header = (
        "# Derek Agent - Provider Configuration\n"
        "# Generated by `derek-agent models`. You may edit this file manually.\n"
        "# API keys stored as ${ENV_VAR} references are read from environment variables.\n\n"
    )

    with path.open("w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(raw, f, allow_unicode=True, default_flow_style=False, sort_keys=False)


# ---------------------------------------------------------------------------
# Model factory
# ---------------------------------------------------------------------------

MINIMAX_MODELS: list[ModelInfo] = [
    ModelInfo(id="MiniMax-M2.7", name="MiniMax M2.7", context_window=204800, reasoning=True),
    ModelInfo(id="MiniMax-M2.7-highspeed", name="MiniMax M2.7 Highspeed", context_window=204800, reasoning=True),
    ModelInfo(id="MiniMax-VL-01", name="MiniMax VL-01 (Vision)", context_window=204800, reasoning=False),
]


def create_model_from_provider(provider_name: str, model_id: str) -> Any:
    """Instantiate an Agno model from providers.yaml config.

    Args:
        provider_name: Provider key, e.g. 'minimax'.
        model_id: Model id, e.g. 'MiniMax-M2.7'.

    Returns:
        Agno model instance.

    Raises:
        ValueError: If provider not configured or api_key missing.
    """
    config = load_providers()
    if provider_name not in config.providers:
        raise ValueError(
            f"Provider '{provider_name}' not configured. Run `derek-agent models` to set it up."
        )

    prov = config.providers[provider_name]
    api_key = _resolve_value(prov.api_key)
    base_url = _resolve_value(prov.base_url) or MINIMAX_DEFAULT_BASE_URL

    if not api_key:
        raise ValueError(
            f"API key for provider '{provider_name}' is empty. "
            "Set the environment variable or run `derek-agent models`."
        )

    protocol = prov.api_protocol.lower()

    if protocol == "anthropic":
        from agno.models.anthropic import Claude
        return Claude(
            id=model_id,
            api_key=api_key,
            client_params={"base_url": base_url},
        )
    elif protocol == "openai":
        from agno.models.openai import OpenAIChat
        return OpenAIChat(id=model_id, api_key=api_key, base_url=base_url)
    else:
        raise ValueError(f"Unsupported api_protocol '{protocol}' for provider '{provider_name}'.")
